#! /usr/bin/python3
import smbus as sm

address = 0x50
bus = sm.SMBus(1)

def writeNumber(value):
    bus.write_byte(address, value)
    return -1

while True:
    data = int(input())
    writeNumber(data)
